version: '3.5'

services:
  app-frontend:
    build:
      context: ./frontend/app-nuxt
      dockerfile: Dockerfile
    environment:
      NITRO_PORT: 80
    ports:
      - "80:80"

  admin-frontend:
    build:
      context: ./frontend/app-vue
      dockerfile: Dockerfile
    ports:
      - "81:80"

  php-laravel-backend:
    container_name: php-laravel-backend
    build:
      context: ./backend/php-laravel
      dockerfile: Dockerfile 
    networks:
      - web-network
    ports:
      - "8000:80"
    depends_on:
      - postgres
    volumes:
      - ./backend/php-laravel/backend-vhost-80.conf:/etc/apache2/sites-available/000-default.conf
      - ./backend/php-laravel:/var/www/html

  admin-php-laravel-backend:
    container_name: admin-php-laravel-backend
    build:
      context: ./backend/admin-php-laravel
      dockerfile: Dockerfile
    networks:
      - web-network
    ports:
      - "8010:80"
    depends_on:
      - postgres
    volumes:
      - ./backend/admin-php-laravel/backend-vhost-80.conf:/etc/apache2/sites-available/000-default.conf
      - ./backend/admin-php-laravel:/var/www/html

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stroy_expert
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - web-network
    ports:
      - "5432:5432"

networks:
  web-network:
    driver: bridge
volumes:
  db-data: