version: '3.5'

services:
  app-frontend:
    build:
      context: ./frontend/app-nuxt
      dockerfile: Dockerfile
    environment:
      NITRO_PORT: 443
    volumes:
      - ./lsk-stroyexpert.ru/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./lsk-stroyexpert.ru/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - "443:443"

  admin-frontend:
    build:
      context: ./frontend/app-vue
      dockerfile: Dockerfile
    volumes:
      - ./lsk-stroyexpert.ru/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./lsk-stroyexpert.ru/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - "444:443"

  php-laravel-backend:
    container_name: php-laravel-backend
    build:
      context: ./backend/php-laravel
      dockerfile: Dockerfile 
    networks:
      - web-network
    ports:
      - "8000:443"
    depends_on:
      - postgres
    volumes:
      - ./backend/php-laravel/backend-vhost-80.conf:/etc/apache2/sites-available/000-default.conf
      - ./backend/php-laravel:/var/www/html
      - ./lsk-stroyexpert.ru/fullchain.pem:/etc/letsencrypt/live/lsk-stroyexpert.ru/fullchain.pem:ro
      - ./lsk-stroyexpert.ru/privkey.pem:/etc/letsencrypt/live/lsk-stroyexpert.ru/privkey.pem:ro

  admin-php-laravel-backend:
    container_name: admin-php-laravel-backend
    build:
      context: ./backend/admin-php-laravel
      dockerfile: Dockerfile
    networks:
      - web-network
    ports:
      - "8010:443"
    depends_on:
      - postgres
    volumes:
      - ./backend/admin-php-laravel/backend-vhost-80.conf:/etc/apache2/sites-available/000-default.conf
      - ./backend/admin-php-laravel:/var/www/html
      - ./lsk-stroyexpert.ru/fullchain.pem:/etc/letsencrypt/live/lsk-stroyexpert.ru/fullchain.pem:ro
      - ./lsk-stroyexpert.ru/privkey.pem:/etc/letsencrypt/live/lsk-stroyexpert.ru/privkey.pem:ro

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db-admin:/var/lib/postgresql/data
    networks:
      - web-network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - web-network
    depends_on:
      - postgres

networks:
  web-network:
    driver: bridge
