version: '3.5'

services:
  app-frontend:
    build:
      context: ./frontend/app-nuxt
      dockerfile: Dockerfile
    environment:
      NITRO_PORT: 80
    ports:
      - "80:80"

  php-laravel-backend:
    container_name: php-laravel-backend
    build:
      context: ./backend/php-laravel
      dockerfile: Dockerfile 
    networks:
      - web-network
    ports:
      - "8000:80"
    depends_on:
      - postgres
    volumes:
      - ./backend/php-laravel/backend-vhost-80.conf:/etc/apache2/sites-available/000-default.conf

  craft-admin:
    container_name: craft-admin
    build:
      context: ./craft-admin
      dockerfile: Dockerfile
    networks:
      - web-network
    ports:
      - "8010:80"
    depends_on:
      - postgres
    volumes:
      - ./craft-admin/backend-vhost-80.conf:/etc/apache2/sites-available/000-default.conf
      - ./craft-admin:/var/www/html

  postgres-admin:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db-admin:/var/lib/postgresql/data
    networks:
      - web-network
    ports:
      - "5432:5432"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - web-network
    ports:
      - "5500:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - web-network
    depends_on:
      - postgres

networks:
  web-network:
    driver: bridge
