services:

  backend:
    container_name: backend
    build: .
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8000:80

  mysql_db:
    container_name: mysql_db_backend
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    # volumes:
    #   - ./backups:/home/backups
    restart: unless-stopped
    ports:
    - 3300:3306